# Generated by Django 3.0.6 on 2020-05-13 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('battery_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('voltage', models.IntegerField()),
                ('current', models.IntegerField()),
                ('polarity', models.CharField(choices=[('П', 'Прямая'), ('О', 'Обратная'), ('ПО', 'Прямая/Обратная'), ('ПиО', 'Прямая и Обратная')], max_length=20)),
                ('size', models.CharField(choices=[('175х175х190', '175х175х190'), ('187х127х227', '187х127х227'), ('207х175х175', '207х175х175'), ('207х175х190', '207х175х190'), ('232х173х190', '232х173х190'), ('232х173х225', '232х173х225'), ('238х129х227', '238х129х227'), ('242х175х175', '242х175х175'), ('242х175х190', '242х175х190'), ('261х175х220', '261х175х220'), ('272х175х175', '272х175х175'), ('278х175х190', '278х175х190'), ('315х175х175', '315х175х175'), ('353х175х190', '353х175х190'), ('390х175х190', '390х175х190'), ('513х189х223', '513х189х223'), ('518х240х242', '518х240х242')], default='none', max_length=15)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('comments', models.CharField(default='-', max_length=200)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
