# Generated by Django 3.0.6 on 2020-05-14 19:54

from django.db import migrations, models
import utils.upload


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='image',
            field=models.ImageField(null=True, upload_to=utils.upload.battery_upload),
        ),
    ]
